version: '3'
services:
#  postgres:
#    image: "debezium/postgres:11"
#    restart: always
#    ports:
#      - "5432:5432"
#    volumes:
#      - "./data:/var/lib/postgresql/data"
#    environment:
#      POSTGRES_DB: hockeystats
#      POSTGRES_USER: hockeystats
#      POSTGRES_PASSWORD: hockeystats
#      PGDATA: /var/lib/postgresql/data
  mongodb:
    image: "mongo:4.2"
    hostname: mongodb
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: hockeystats
      MONGO_INITDB_ROOT_PASSWORD: hockeystats
  zookeeper:
    image: "debezium/zookeeper:0.10"
    restart: always
    ports:
      - "2181:2181"
      - "2888:2888"
      - "3888:3888"
  kafka:
    image: "debezium/kafka:0.10"
    restart: always
    links:
      - zookeeper
    environment:
      - ZOOKEEPER_CONNECT=zookeeper:2181
    ports:
      - "9092:9092"
  debezium:
    image: "debezium/connect:0.10"
    restart: always
    ports:
      - "8083:8083"
    links:
      - zookeeper
      - kafka
      - mongodb
    environment:
      BOOTSTRAP_SERVERS: kafka:9092
      GROUP_ID: debezium
      CONFIG_STORAGE_TOPIC: debezium_configurations
      OFFSET_STORAGE_TOPIC: debezium_offsets
      STATUS_STORAGE_TOPIC: debezium_statuses
