version: '3'
services:
  postgres:
    image: "postgres:12"
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - "./data:/var/lib/postgresql/data"
      - "./postgres-init.sh:/docker-entrypoint-initdb.d/postgres-init.sh"
    environment:
      POSTGRES_DB: hockeystats
      POSTGRES_USER: hockeystats
      POSTGRES_PASSWORD: hockeystats
      PGDATA: /var/lib/postgresql/data
