version: '3'
services:
  mongodb:
    image: "mongo:4.2"
    hostname: mongodb
    ports:
      - 27017:27017
    volumes:
      - "./data/mongo:/data/db"
    environment:
      MONGO_INITDB_ROOT_USERNAME: hockeystats
      MONGO_INITDB_ROOT_PASSWORD: hockeystats
